[package]
name = "mcp_server_exa_search"
version = "0.0.2"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/mcp_server_exa_search.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
schemars = "0.8"
zed_extension_api = "0.5.0"
